#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/chrony
- ansible.builtin.import_tasks: install.yml
- ansible.builtin.import_tasks: configure.yml
- ansible.builtin.import_tasks: service.yml
